version: '3'
services:

  mongo:
    image: mongo:4.4.13
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    ports:
      - '27017:27017'
    volumes:
      - mongo:/var/lib/mongo

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379

  influxdb:
    image: quay.io/influxdb/influxdb:v2.0.3
    restart: always
    volumes:
      # Mount for influxdb data directory and configuration
      - influxdbv2:/.influxdbv2
    expose:
      - 8086
    ports:
      - "8086:8086"

  minio:
    image: quay.io/minio/minio
    restart: always
    expose:
      - "9000"
      - "9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_data1:/data1
      - ./minio_data2:/data2
      - ./minio_data3:/data3
      - ./minio_data4:/data4
    environment:
      MINIO_ROOT_USER: $MINIO_USERNAME
      MINIO_ROOT_PASSWORD: $MINIO_PASSWORD
    command: server /data{1...4} --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  vault:
    image: vault:latest
    volumes:
      - ./vault/config:/vault/config
      - vault:/vault
    ports:
      - 8200:8200
    expose:
      - '8200'
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_API_ADDR=http://0.0.0.0:8200
      - VAULT_ADDRESS=http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    command: vault server -config=/vault/config/vault.json

  fastapi:
      image: okazdal/automatik-backend:0.1
      restart: always
      expose:
        - "8000"
      ports:
        - 8000:8000
      volumes:
        - ./config/config.py:/usr/src/app/config.py
        - ./.env:/usr/src/app/.env
      command: 
        "python app_starter.py"

  sio:
    image: okazdal/automatik-backend:0.1
    restart: always
    expose:
      - "8000"
    ports:
      - 8001:8000
    volumes:
      - ./config/config.py:/usr/src/app/config.py
      - ./.env:/usr/src/app/.env
    command:
      "python sio_tornado_starter.py"

  worker:
    image: okazdal/automatik-backend:0.1
    restart: always
    command:
      "celery -A task_queue worker -l info -E"
    volumes:
      - ./config/config.py:/usr/src/app/config.py
      - backups:/usr/src/app/backups
      - ./.env:/usr/src/app/.env

  beat:
    image: okazdal/automatik-backend:0.1
    restart: always
    volumes:
      - ./config/config.py:/usr/src/app/config.py
      - ./.env:/usr/src/app/.env
    command:
      "celery -A task_queue beat -l info"

  frontend:
    image: okazdal/automatik-frontend:0.1
    restart: always
    ports:
      - 80:80
     

volumes:
  mongo:
  influxdbv2:
  backups:
  vault: