version: '3'
services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    ports:
      - '27017:27017'
    volumes:
      - mongo:/var/lib/mongo

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379

  influxdb:
    image: quay.io/influxdb/influxdb:v2.0.3
    restart: always
    volumes:
      # Mount for influxdb data directory and configuration
      - influxdbv2:/.influxdbv2
    expose:
      - 8086
    ports:
      - "8086:8086"

  minio:
    image: quay.io/minio/minio
    restart: always
    expose:
      - "9000"
      - "9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_data1:/data1
      - ./minio_data2:/data2
      - ./minio_data3:/data3
      - ./minio_data4:/data4
    environment:
      MINIO_ROOT_USER: $MINIO_USERNAME
      MINIO_ROOT_PASSWORD: $MINIO_PASSWORD
    command: server /data{1...4} --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  vault:
    image: vault:latest
    volumes:
      - ./vault/config:/vault/config
      - ./vault/policies:/vault/policies
      - ./vault/data:/vault/data
      - ./vault/db:/mnt/vault/data
    ports:
      - 8200:8200
    expose:
      - '8200'
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_API_ADDR=http://0.0.0.0:8200
      - VAULT_ADDRESS=http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    command: vault server -config=/vault/config/vault.json


volumes:
  mongo:
  influxdbv2: